[workspace]
[package]
version = "0.1.0"
name = "store-tree-program"
edition = "2021"

[dependencies]
sp1-zkvm = { git = "https://github.com/delehef/sp1.git" }
buf-view = "0.1.0"
blake2 = "0.10"
hex = "0.4"

[dependencies.sha256]
version = "1.5"
default-features = false
